services:
  mongo:
    image: mongo:7.0.9
    restart: always
    env_file: ".mongo.env"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "mongo_data:/data/db"

  muskrat:
    build: .
    restart: always
    env_file: ".muskrat.env"
    ports:
      - "50052:50052"

volumes:
  mongo_data:
