// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.2
// source: raidService.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaidInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BossName string `protobuf:"bytes,1,opt,name=bossName,proto3" json:"bossName,omitempty"`
	Cell     string `protobuf:"bytes,2,opt,name=cell,proto3" json:"cell,omitempty"`
	Time     int32  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *RaidInfo) Reset() {
	*x = RaidInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raidService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaidInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaidInfo) ProtoMessage() {}

func (x *RaidInfo) ProtoReflect() protoreflect.Message {
	mi := &file_raidService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaidInfo.ProtoReflect.Descriptor instead.
func (*RaidInfo) Descriptor() ([]byte, []int) {
	return file_raidService_proto_rawDescGZIP(), []int{0}
}

func (x *RaidInfo) GetBossName() string {
	if x != nil {
		return x.BossName
	}
	return ""
}

func (x *RaidInfo) GetCell() string {
	if x != nil {
		return x.Cell
	}
	return ""
}

func (x *RaidInfo) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raidService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_raidService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_raidService_proto_rawDescGZIP(), []int{1}
}

var File_raidService_proto protoreflect.FileDescriptor

var file_raidService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x61, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x61, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x4e, 0x0a, 0x08, 0x52, 0x61, 0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x6f, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x6f, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x6c, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x65, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x22, 0x06, 0x0a, 0x04, 0x4e, 0x75, 0x6c, 0x6c, 0x32, 0x41, 0x0a, 0x04, 0x52, 0x61, 0x69, 0x64,
	0x12, 0x39, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x61, 0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x15, 0x2e, 0x72, 0x61, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x61,
	0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x11, 0x2e, 0x72, 0x61, 0x69, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x75, 0x73, 0x73, 0x69, 0x61,
	0x39, 0x2f, 0x4d, 0x75, 0x73, 0x6b, 0x72, 0x61, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_raidService_proto_rawDescOnce sync.Once
	file_raidService_proto_rawDescData = file_raidService_proto_rawDesc
)

func file_raidService_proto_rawDescGZIP() []byte {
	file_raidService_proto_rawDescOnce.Do(func() {
		file_raidService_proto_rawDescData = protoimpl.X.CompressGZIP(file_raidService_proto_rawDescData)
	})
	return file_raidService_proto_rawDescData
}

var file_raidService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raidService_proto_goTypes = []any{
	(*RaidInfo)(nil), // 0: raidService.RaidInfo
	(*Null)(nil),     // 1: raidService.Null
}
var file_raidService_proto_depIdxs = []int32{
	0, // 0: raidService.Raid.GetRaidInfo:input_type -> raidService.RaidInfo
	1, // 1: raidService.Raid.GetRaidInfo:output_type -> raidService.Null
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_raidService_proto_init() }
func file_raidService_proto_init() {
	if File_raidService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_raidService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RaidInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raidService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_raidService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raidService_proto_goTypes,
		DependencyIndexes: file_raidService_proto_depIdxs,
		MessageInfos:      file_raidService_proto_msgTypes,
	}.Build()
	File_raidService_proto = out.File
	file_raidService_proto_rawDesc = nil
	file_raidService_proto_goTypes = nil
	file_raidService_proto_depIdxs = nil
}
